### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by Tamir198**
Resizing the images so they will be in the same size
Fixing some indentation

### CODE REVIEW

**Comment by MohammedAlaaMorsi** [comment]
Hi @Tamir198  could you make the images bigger a little bit , so the views will be appears clearly, and I will be happy to merge the PR

**Comment by Tamir198** [comment]
> Hi @Tamir198 could you make the images bigger a little bit , so the views will be appears clearly, and I will be happy to merge the PR

Done

**Comment by MohammedAlaaMorsi** [comment]
Hi @Tamir198  sorry for inconvenience, I see that the images are looking to big , can you make it ` height="620"` `width="320"` and put it at the top after use section to center alignment , this will be better as you can see the library result at the top of page

**Comment by Tamir198** [comment]
> Hi @Tamir198 sorry for inconvenience, I see that the images are looking to big , can you make it ` height="620"` `width="320"` and put it at the top after use section to center alignment , this will be better as you can see the library result at the top of page

I will open a new pr

**Pull request merged**
